import { ModelCatalogItem } from '../types.js';

export const MODELS_CATALOG: ModelCatalogItem[] = [
  // 1. Texto Geral
  {
    order: 1,
    id: 'gemini-3.8-flash',
    name: 'Gemini 3.8 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'text',
    groupName: '1. Modelos de Texto Geral',
    description: 'Prioridade máxima para tarefas de raciocínio crítico, auditoria rigorosa de código e segurança.',
    recommendedRole: 'Auditor',
  },
  {
    order: 2,
    id: 'gemini-3.7-flash',
    name: 'Gemini 3.7 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'text',
    groupName: '1. Modelos de Texto Geral',
    description: 'Raciocínio híbrido e diagnóstico investigativo detalhado com coleta de evidências.',
    recommendedRole: 'Investigator',
  },
  {
    order: 3,
    id: 'gemini-3.6-flash',
    name: 'Gemini 3.6 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'text',
    groupName: '1. Modelos de Texto Geral',
    description: 'Decisões arquiteturais, design de sistemas, modularidade e desacoplamento de software.',
    recommendedRole: 'Architect',
  },
  {
    order: 4,
    id: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'text',
    groupName: '1. Modelos de Texto Geral',
    description: 'Equilíbrio sólido para geração de código e operações de texto multimodais.',
  },
  {
    order: 5,
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'text',
    groupName: '1. Modelos de Texto Geral',
    description: 'Validação ágil de comportamentos, construção de suítes de testes e checagem de regressões.',
    recommendedRole: 'Tester',
  },
  {
    order: 6,
    id: 'gemini-3.1-flash-lite',
    name: 'Gemini 3.1 Flash Lite',
    rpm: '0 / 150',
    tpm: '250K',
    rpd: '0 / 500',
    category: 'Txt Out',
    group: 'text',
    groupName: '1. Modelos de Texto Geral',
    description: 'Alta cadência de requisições, refatoração de boilerplate e tarefas repetitivas.',
    recommendedRole: 'Worker',
  },
  {
    order: 7,
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'text',
    groupName: '1. Modelos de Texto Geral',
    description: 'Geração estável consolidada para produção com ferramentas padrão.',
  },
  {
    order: 8,
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash Lite',
    rpm: '0 / 100',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Txt Out',
    group: 'text',
    groupName: '1. Modelos de Texto Geral',
    description: 'Versão ultra-leve para processamento rápido e baixo overhead.',
  },
  {
    order: 9,
    id: 'gemini-3.5-flash-lite',
    name: 'Gemini 3.5 Flash Lite',
    rpm: '1 / 1521',
    tpm: '250K',
    rpd: '1 / 500',
    category: 'Txt Out',
    group: 'text',
    groupName: '1. Modelos de Texto Geral',
    description: 'Coordenação geral, roteamento e maior teto de requisições disponíveis por minuto.',
    recommendedRole: 'Principal / Orchestrator',
  },

  // 2. Voz, transcrição, tradução e áudio em tempo real
  {
    order: 1,
    id: 'gemini-3.5-transcribe-live',
    name: 'Gemini 3.5 Transcribe Live',
    rpm: '0 / Inf',
    tpm: '0 / 20K',
    rpd: '0 / Inf',
    category: 'API Live',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Transcrição (fala → texto em tempo real)',
    description: 'Streaming contínuo de áudio com baixa latência para transcrição ao vivo.',
  },
  {
    order: 2,
    id: 'gemini-3.5-live-translate',
    name: 'Gemini 3.5 Live Translate',
    rpm: '0 / Inf',
    tpm: '0 / 20K',
    rpd: '0 / Inf',
    category: 'API Live',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Tradução de voz em tempo real',
    description: 'Tradução simultânea bidirecional de voz em tempo real.',
  },
  {
    order: 3,
    id: 'gemini-3-flash-live',
    name: 'Gemini 3 Flash Live',
    rpm: '0 / Inf',
    tpm: '0 / 65K',
    rpd: '0 / Inf',
    category: 'API Live',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Conversação de áudio em tempo real',
    description: 'Diálogo fluido por áudio em streaming contínuo bidirecional.',
  },
  {
    order: 4,
    id: 'gemini-3.5-transcribe',
    name: 'Gemini 3.5 Transcribe',
    rpm: '1 / 36',
    tpm: '10K',
    rpd: '1 / 255',
    category: 'API Live',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Transcrição (fala → texto)',
    description: 'Motor oficial de Speech-to-Text (STT) utilizado no ditado da interface.',
  },
  {
    order: 5,
    id: 'gemini-3.1-flash-tts',
    name: 'Gemini 3.1 Flash TTS',
    rpm: '0 / 30',
    tpm: '10K',
    rpd: '0 / 106',
    category: 'Multimod',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Síntese de voz (texto → fala)',
    description: 'Síntese natural de respostas em áudio multivozes (Kore, Puck, Fenrir).',
  },
  {
    order: 6,
    id: 'gemini-2.5-flash-native-audio-dialog',
    name: 'Gemini 2.5 Flash Native Audio Dialog',
    rpm: '0 / Inf',
    tpm: '1M',
    rpd: '0 / Inf',
    category: 'API Live',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Conversação de áudio em tempo real',
    description: 'Diálogo de voz nativo com contexto amplo de 1M tokens.',
  },
  {
    order: 7,
    id: 'gemini-2.5-flash-tts',
    name: 'Gemini 2.5 Flash TTS',
    rpm: '0 / 30',
    tpm: '10K',
    rpd: '0 / 10',
    category: 'Multimod',
    group: 'audio',
    groupName: '2. Voz, transcrição, tradução e áudio em tempo real',
    subFunction: 'Síntese de voz (texto → fala)',
    description: 'Síntese de fala estável para leituras de respostas.',
  },

  // 3. Agentes e automação
  {
    order: 1,
    id: 'antigravity',
    name: 'Antigravity',
    rpm: '0 / 600',
    tpm: '100K',
    rpd: '0 / 100',
    category: 'Agents',
    group: 'agents',
    groupName: '3. Agentes e automação',
    subFunction: 'Motor nativo dedicado para Agents autônomos',
    description: 'O único modelo/serviço explicitamente destinado a Agents e fluxos autônomos complexos.',
  },

  // 4. Robótica
  {
    order: 1,
    id: 'gemini-robotics-er-2-preview',
    name: 'Gemini Robotics ER 2 Preview',
    rpm: '0 / 50',
    tpm: '250K',
    rpd: '0 / 20',
    category: 'Outros',
    group: 'robotics',
    groupName: '4. Robótica',
    subFunction: 'Embodied AI e controle robótico',
    description: 'Modelo especializado para tarefas espaciais e visão robótica embodied.',
  },

  // 5. Embeddings / busca semântica / representação vetorial
  {
    order: 1,
    id: 'gemini-embedding-2',
    name: 'Gemini Embedding 2',
    rpm: '0 / 1000',
    tpm: '30K',
    rpd: '0 / 1K',
    category: 'Outros',
    group: 'embeddings',
    groupName: '5. Embeddings / busca semântica',
    subFunction: 'Vetores de alta densidade semântica',
    description: 'Embeddings modernos para indexação e busca semântica em bases de código.',
  },
  {
    order: 2,
    id: 'gemini-embedding-1',
    name: 'Gemini Embedding 1',
    rpm: '0 / 1000',
    tpm: '30K',
    rpd: '0 / 1K',
    category: 'Outros',
    group: 'embeddings',
    groupName: '5. Embeddings / busca semântica',
    subFunction: 'Vetores semânticos padrão',
    description: 'Embeddings estáveis para comparação de similaridade vetorial.',
  },

  // 6. Modelos abertos / gerais da família Gemma
  {
    order: 1,
    id: 'gemma-4-31b',
    name: 'Gemma 4 31B',
    rpm: '0 / 300',
    tpm: '16K',
    rpd: '0 / 14.4K',
    category: 'Outros',
    group: 'gemma',
    groupName: '6. Modelos abertos Gemma',
    subFunction: 'Modelo aberto de alta densidade (31B)',
    description: 'Família aberta Gemma 4 para execução descentralizada e auditoria local.',
  },
  {
    order: 2,
    id: 'gemma-4-26b',
    name: 'Gemma 4 26B',
    rpm: '0 / 300',
    tpm: '16K',
    rpd: '0 / 14.4K',
    category: 'Outros',
    group: 'gemma',
    groupName: '6. Modelos abertos Gemma',
    subFunction: 'Modelo aberto balanceado (26B)',
    description: 'Família aberta Gemma 4 otimizada para tarefas pontuais de desenvolvimento.',
  },
];
